### ISSUE TITLE
Unit tests not in tests directory - needs reorganization

### ISSUE THREAD

**Issue by aburrell** [drsteve/PyForecastTools#6]
Missing unit tests for the functions.

**Comment by drsteve** [comment]
I know there's a tests directory that just contains a stub, but there's pretty comprehensive testing in the test_verify.py file in the base directory. I need to reorg that. Let me know if you were getting at something else, otherwise I'll close this in the near future.

**Comment by aburrell** [comment]
Nope, that's what I was getting at.  A re-org would deal with this issue.

**Comment by drsteve** [comment]
Then I'll leave this issue open, but rename it.

FYI, I've been re-organizing the stuff in the verify directory in a separate branch (EDA-plots), mostly because I wanted to add new features and it seemed like the right opportunity to break everything out of the __init__ (which I know you had mentioned). Take a look at that and let me know if it's looking better... I have a little more work to do, but I plan on merging it back into master soon.

That doesn't include a test re-org, but it does go some way to making the package a little better structured.

**Comment by drsteve** [comment]
Closed by commit 0fdf875.

Tests moved to test directory.
Travis CI switched to using pytest for test discovery.
